### ISSUE TITLE
Problem with getblocktemplate on testnet

### ISSUE THREAD

**Issue by wiiiteek** [DigiByte-Core/digibyte#245]
Hi,

When I am running node on test chain (`./digibyted -testnet`) I cant generate block template for mining. I am receiving error

```
error code: -9
error message:
DigiByte is not connected!
```

But node seems to run OK, because other method `getmininginfo` for example returns this data

```
{
  "blocks": 0,
  "currentblockweight": 0,
  "pow_algo_id": 1,
  "pow_algo": "scrypt",
  "difficulty": 0.000244140625,
  "difficulty_scrypt": 0.000244140625,
  "errors": "",
  "pooledtx": 0,
  "chain": "test",
  "warnings": ""
}
```
also test chain seems to be empty because on node logs there is only one block with heigh=0
```
2024-06-21T10:22:53Z Loaded best chain: hashBestChain=308ea0711d5763be2995670dd9ca9872753561285a84da1d58be58acaa822252 height=0 date=2018-01-26T04:04:34Z progress=0.000000
```

Is there something wrong with my setup or maybe DigiByte does not have a working testnet chain?

**Comment by beggsdl** [comment]
Hello wiiiteek. Testnet is absolutely working. I have been mining about 99% of the testnet blocks for most of this year. What DigiByte version are you running?

**Comment by wiiiteek** [comment]
Hi,

I am running latest `digibyte-7.17.3` with these arguments `./digibyted -testnet -rpcpassword=qqqqqq -rpcuser=wiktor -rpcport=6969`

Here are node logs

```
2024-06-21T10:50:42Z DigiByte Core version v7.17.3 (release build)
2024-06-21T10:50:42Z InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
2024-06-21T10:50:42Z Validating signatures for all blocks.
2024-06-21T10:50:42Z Setting nMinimumChainWork=0000000000000000000000000000000000000000000000000000000000000000
2024-06-21T10:50:42Z Using the 'sse4(1way),sse41(4way)' SHA256 implementation
2024-06-21T10:50:42Z Default data directory /home/wiktor/.digibyte
2024-06-21T10:50:42Z Using data directory /home/wiktor/.digibyte/testnet4
2024-06-21T10:50:42Z Using config file /home/wiktor/.digibyte/digibyte.conf
2024-06-21T10:50:42Z Using at most 125 automatic connections (1024 file descriptors available)
2024-06-21T10:50:42Z Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
2024-06-21T10:50:42Z Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
2024-06-21T10:50:42Z Using 16 threads for script verification
2024-06-21T10:50:42Z scheduler thread start
2024-06-21T10:50:42Z HTTP: creating work queue of depth 16
2024-06-21T10:50:42Z Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcauth for rpcauth auth generation.
2024-06-21T10:50:42Z HTTP: starting 4 worker threads
2024-06-21T10:50:42Z Using wallet directory /home/wiktor/.digibyte/testnet4/wallets
2024-06-21T10:50:42Z init message: Verifying wallet(s)...
2024-06-21T10:50:42Z Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2024-06-21T10:50:42Z Using wallet wallet.dat
2024-06-21T10:50:42Z BerkeleyEnvironment::Open: LogDir=/home/wiktor/.digibyte/testnet4/wallets/database ErrorFile=/home/wiktor/.digibyte/testnet4/wallets/db.log
2024-06-21T10:50:42Z Selected Algo: scrypt
2024-06-21T10:50:42Z Cache configuration:
2024-06-21T10:50:42Z * Using 2.0MiB for block index database
2024-06-21T10:50:42Z * Using 8.0MiB for chain state database
2024-06-21T10:50:42Z * Using 440.0MiB for in-memory UTXO set (plus up to 286.1MiB of unused mempool space)
2024-06-21T10:50:42Z init message: Loading block index...
2024-06-21T10:50:42Z Opening LevelDB in /home/wiktor/.digibyte/testnet4/blocks/index
2024-06-21T10:50:42Z Opened LevelDB successfully
2024-06-21T10:50:42Z Using obfuscation key for /home/wiktor/.digibyte/testnet4/blocks/index: 0000000000000000
2024-06-21T10:50:42Z LoadBlockIndexDB: last block file = 0
2024-06-21T10:50:42Z LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=0, size=0, heights=0...0, time=1970-01-01...1970-01-01)
2024-06-21T10:50:42Z Checking all blk files are present...
2024-06-21T10:50:42Z Initializing databases...
2024-06-21T10:50:42Z Pre-allocating up to position 0x1000000 in blk00000.dat
2024-06-21T10:50:42Z Opening LevelDB in /home/wiktor/.digibyte/testnet4/chainstate
2024-06-21T10:50:42Z Opened LevelDB successfully
2024-06-21T10:50:42Z Wrote new obfuscate key for /home/wiktor/.digibyte/testnet4/chainstate: b1c5695e68f957fb
2024-06-21T10:50:42Z Using obfuscation key for /home/wiktor/.digibyte/testnet4/chainstate: b1c5695e68f957fb
2024-06-21T10:50:42Z init message: Rewinding blocks...
2024-06-21T10:50:42Z  block index              90ms
2024-06-21T10:50:42Z init message: Loading wallet...
2024-06-21T10:50:42Z [default wallet] nFileVersion = 7170300
2024-06-21T10:50:42Z [default wallet] Keys: 0 plaintext, 0 encrypted, 0 w/ metadata, 0 total. Unknown wallet records: 0
2024-06-21T10:50:42Z [default wallet] Performing wallet upgrade to 169900
2024-06-21T10:50:43Z [default wallet] keypool added 2000 keys (1000 internal), size=2000 (1000 internal)
2024-06-21T10:50:43Z [default wallet] Wallet completed loading in            1495ms
2024-06-21T10:50:43Z [default wallet] setKeyPool.size() = 2000
2024-06-21T10:50:43Z [default wallet] mapWallet.size() = 0
2024-06-21T10:50:43Z [default wallet] mapAddressBook.size() = 0
2024-06-21T10:50:43Z UpdateTip: new best=308ea0711d5763be2995670dd9ca9872753561285a84da1d58be58acaa822252 height=0 version=0x00000001 algo=1 (scrypt) log2_work=20.000022 tx=1 date='2018-01-26T04:04:34Z' progress=0.000000 cache=0.0MiB(0txo)
2024-06-21T10:50:43Z mapBlockIndex.size() = 1
2024-06-21T10:50:43Z Failed to open mempool file from disk. Continuing anyway.
2024-06-21T10:50:43Z nBestHeight = 0
2024-06-21T10:50:43Z torcontrol thread start
2024-06-21T10:50:43Z Bound to [::]:12026
2024-06-21T10:50:43Z Bound to 0.0.0.0:12026
2024-06-21T10:50:43Z init message: Loading P2P addresses...
2024-06-21T10:50:43Z ERROR: DeserializeFileDB: Failed to open file /home/wiktor/.digibyte/testnet4/peers.dat
2024-06-21T10:50:43Z Invalid or missing peers.dat; recreating
2024-06-21T10:50:43Z init message: Loading banlist...
2024-06-21T10:50:43Z ERROR: DeserializeFileDB: Failed to open file /home/wiktor/.digibyte/testnet4/banlist.dat
2024-06-21T10:50:43Z Invalid or missing banlist.dat; recreating
2024-06-21T10:50:43Z init message: Starting network threads...
2024-06-21T10:50:43Z net thread start
2024-06-21T10:50:43Z dnsseed thread start
2024-06-21T10:50:43Z addcon thread start
2024-06-21T10:50:43Z Loading addresses from DNS seeds (could take a while)
2024-06-21T10:50:43Z opencon thread start
2024-06-21T10:50:43Z msghand thread start
2024-06-21T10:50:43Z init message: Done loading
2024-06-21T10:50:43Z dandelion thread start
2024-06-21T10:50:44Z 0 addresses found from DNS seeds
2024-06-21T10:50:44Z dnsseed thread exit
2024-06-21T10:51:44Z Adding fixed seed nodes as DNS doesn't seem to be available.
2024-06-21T11:01:57Z Potential stale tip detected, will try using extra outbound peer (last tip update: 674 seconds ago)
```

**Comment by saltedlolly** [comment]
If you are running 7.17.3 you will need to manually add another node to connect to, since the old seed servers are all offline. I would recommend running 8.22.0-rc4 which has solved this issue.

**Comment by wiiiteek** [comment]
Ok, with `8.22.0-rc4` node started syncing with other nodes but unfortunately it throws `Segmentation fault` after few seconds of working

```
...
2024-06-21T11:21:05Z UpdateTip: new best=d5756e61b61d903e5a4596dd93a57c771ae95662da6ce930d6a0f8f809603326 height=30 version=0x20000002 algo=1 (scrypt) log2_work=24.954198 tx=31 date='2019-04-03T04:15:53Z' progress=0.000009 cache=0.0MiB(30txo)
2024-06-21T11:21:05Z UpdateTip: new best=623bf0fec40614190caf77fc8f92b6a064aac0a21ae5732606e539e7f1323426 height=31 version=0x20000002 algo=1 (scrypt) log2_work=25.000002 tx=32 date='2019-04-03T04:19:55Z' progress=0.000009 cache=0.0MiB(31txo)
2024-06-21T11:21:05Z UpdateTip: new best=8f28efa8820bc5614efb954810fb68b37e47608bd0ebcc80d26b22a7d8afeae6 height=32 version=0x20000002 algo=1 (scrypt) log2_work=25.044396 tx=33 date='2019-04-03T04:29:52Z' progress=0.000010 cache=0.0MiB(32txo)
2024-06-21T11:21:05Z Loading addresses from DNS seed testnet.digibyteseed.com
Naruszenie ochrony pamięci (zrzut pamięci) <-- Segmentation fault
```

**Comment by beggsdl** [comment]
@wiiiteek  Am I correct that you have gotten mining working?  I appear to be getting only 60% of the blocks now.

**Comment by JaredTate** [comment]
> @wiiiteek Am I correct that you have gotten mining working? I appear to be getting only 60% of the blocks now.

Other new blocks are skein blocks we are having loads of issues with.

We have been working to set up testnet nodes and test mine on DigiHash. It appears testnet was never set up properly this last time and is throwing unknown version bit errors. There are lots of issues mining odo/ skein/ qubit which is why it appears only sha and script were getting mined. The soft forks/ hard forks were not executed in the correct steps. Also with 3 million + blocks, sync times are way too long for testing now. So for many reasons, it's time to reset the testnet and start over. We need to tweak several testnet settings.

I was told others had test-mined all 5 algos on previous 8.22 versions, but that does not appear to be the case. It's all good, we will just need a group effort to get tesnet reset and these bugs sorted. It's important to have all 5 mining algos continuously mined on testnet if we are going to keep testnet going.

I should also mention to anyone looking to use testnet, outside of mining testing and p2p issues testing all of your test needs can be done with reg test. Reg test will fulfill 99% of any issues trying to build on top of DGB. Bitcoin devs had tons of issues with testnet like we are which is why regtest was created.

> For situations where interaction with random peers and blocks is unnecessary or unwanted, Bitcoin Core’s regression test mode (regtest mode) lets you instantly create a brand-new private blockchain with the same basic rules as testnet—but one major difference: you choose when to create new blocks, so you have complete control over the environment.

> Many developers consider regtest mode the preferred way to develop new applications. The following example will let you create a regtest environment after you first [configure bitcoind](https://developer.bitcoin.org/examples/index.html).

https://developer.bitcoin.org/examples/testing.html

![signal-2024-06-20-153145_008](https://github.com/DigiByte-Core/digibyte/assets/13957390/4650bd27-a9eb-4c25-ab97-380c1edb2fdc)

![signal-2024-06-20-155402_006](https://github.com/DigiByte-Core/digibyte/assets/13957390/ba91d2f4-c220-4330-9d12-9e5775056ba3)

![signal-2024-06-20-140725_012](https://github.com/DigiByte-Core/digibyte/assets/13957390/e57a7544-8406-4843-8a11-814888b89226)

**Comment by JaredTate** [comment]
> @wiiiteek Am I correct that you have gotten mining working? I appear to be getting only 60% of the blocks now.

Also I did not realize you were the one keeping testnet alive. Thank you for that and thanks for helping keep it going for people to test. We will try and get a couple more CPU miners and a testnet mining pool for all 5 algos on digihash moving forward to support community testing.

**Comment by JaredTate** [comment]
What is absolutely mind boggling is we are mining skein blocks that get added to the testnet chain yet the 8.22 RC4 digibyted rejects the skein blocks as invalid, no funds are sent to reward wallet, or held in pool wallet and 8.22 RC4 client rejects the mined blocks. 

Yet the blocks are still added to the chain and it keeps incrementing. So 100% this is a testnet consensus rules issue as we testmined Skien, qubit on main net with 8.22 RC4 just fine. 

> 2024-06-21 15:49:38 [Pool]	[testnet-skein] (Thread 1) Submitted Block using submitblock successfully to daemon instance(s)
2024-06-21 15:49:38 [Pool]	[testnet-skein] (Thread 1) We thought a block was found but it was rejected by the daemon, share data: {"job":"7b8","ip":"::ffff:66.64.43.14","port":4011,"worker":"yhB2Tjcpn1bc7qzSbsaHFN7PwsNtxwpBKG","height":3168021,"blockReward":88122866626,"difficulty":0.1,"shareDiff":"0.22217868","blockDiff":0.004663207,"blockDiffActual":0.004663207,"blockHash":"0000000480354c860a1803eafbb7c9aef72434c6878f7a256043d9af40bb80bf"}

Just restarted skein miner again to debug, running my stats site on testnet locally is kinda handy:

![Screenshot 2024-06-21 at 2 48 34 PM](https://github.com/DigiByte-Core/digibyte/assets/13957390/cdfcde76-8eff-4b4e-b614-c657ac5f9a17)

![signal-2024-06-21-094350_008](https://github.com/DigiByte-Core/digibyte/assets/13957390/bdc5f76d-62aa-4b02-af2f-30d70e0e085c)

**Comment by beggsdl** [comment]
@JaredTate Yes, I had been mining sha256, scrypt, and skein for quite a while. Skein stopped a little while back when I had a power outage. I previously had mined all 5 algos by manually switching my miner periodically. Right now I just mined a few skein blocks and a couple odo blocks. And now a handful of Qubit blocks.

**Comment by JaredTate** [comment]
> @JaredTate Yes, I had been mining sha256, scrypt, and skein for quite a while. Skein stopped a little while back when I had a power outage. I previously had mined all 5 algos by manually switching my miner periodically. Right now I just mined a few skein blocks and a couple odo blocks. And now a handful of Qubit blocks.

Thanks for doing that, I know that's a big hassle to keep that many miners going on testnet. I was under the impression a few people were doing that to help, not just 1 person. We can start from now on to help out. We can get 2-3 more of us to run a CPU miner.

Here is where we are setting the 5 testmining algos up on digihash. https://digihash.digibyte.io/

What wallet version are you mining with @beggsdl? I assume you are mining straight to your wallet? Trying to debug this version bit 6 issue on testnet. See if we can't do an easier reset of it than a full blown testnet reset.

Thanks for helping us debug this. 

We also want to double-check check we don't have any 8.22 issues with odo as we can't seem to mine an 8.22 RC4 odo block on main net. This will also help us debug digihash pool too. Cheers

**Comment by JaredTate** [comment]
> @JaredTate Yes, I had been mining sha256, scrypt, and skein for quite a while. Skein stopped a little while back when I had a power outage. I previously had mined all 5 algos by manually switching my miner periodically. Right now I just mined a few skein blocks and a couple odo blocks. And now a handful of Qubit blocks.

I see the other blocks now, are you mining on 8.22 RC4? Or 7.17.3? We may have an issue with digihash pool... very strange behavior, but that still would not explain the error in the 8.22 rc4 testnet client itself.
![Screenshot 2024-06-21 at 3 56 21 PM](https://github.com/DigiByte-Core/digibyte/assets/13957390/91e042c3-02f6-4d54-b20d-e2e42bc01c61)

**Comment by beggsdl** [comment]
I have to check the version on my Linux box where I mined the odo, qubit, and skein blocks. I know it is 8.22.x, just not positive if it’s rc4 or not. My Windows machine mining scrypt and sha256 is rc4.

**Comment by JaredTate** [comment]
> I have to check the version on my Linux box where I mined the odo, qubit, and skein blocks. I know it is 8.22.x, just not positive if it’s rc4 or not. My Windows machine mining scrypt and sha256 is rc4.

Ok good to know, our issue could be DigiHash... very strange though. Are you getting the version bits warning? I am getting it on 3 separate 8.22 RC4 test wallets now. We are going to try to test mine sha, scrypt and qubit through pool here in a bit when they finish syncing. Try and get a block on all 5 algos. Something in testnet consensus rules appears off vs main net. Looking through the previous soft forks testnet code they may not have been ran through in correct order when testnet was reset the last time.

**Comment by beggsdl** [comment]
> Ok good to know, our issue could be DigiHash... very strange though. Are you getting the version bits warning? I am getting it on 3 separate 8.22 RC4 test wallets now. We are going to try to test mine sha, scrypt and qubit through pool here in a bit when they finish syncing. Try and get a block on all 5 algos. Something in testnet consensus rules appears off vs main net. Looking through the previous soft forks testnet code they may not have been ran through in correct order when testnet was reset the last time.

Yes, I do see the version bits warning. I have I think at least since we fixed that split chain issue around Christmas/New Year’s.

**Comment by JaredTate** [comment]
> > Ok good to know, our issue could be DigiHash... very strange though. Are you getting the version bits warning? I am getting it on 3 separate 8.22 RC4 test wallets now. We are going to try to test mine sha, scrypt and qubit through pool here in a bit when they finish syncing. Try and get a block on all 5 algos. Something in testnet consensus rules appears off vs main net. Looking through the previous soft forks testnet code they may not have been ran through in correct order when testnet was reset the last time.
> 
> Yes, I do see the version bits warning. I have I think at least since we fixed that split chain issue around Christmas/New Year’s.

That could be another reason to reset the testnet chain. It may go away if we get 8.22 RC4 mining all 5 algos for a bit. Will have to try it. Just curious if we have an older client mining a bunch of blocks still. 

More importantly, it is good to double-check check there is still not another issue in 8.22 to flush out. So I will keep debuggingg.

**Comment by JaredTate** [comment]
> 2024-06-21 22:28:01 [Pool]	[testnet-sha256] (Thread 10) Could not parse rpc data from daemon instance  0
Request Data: {"method":"getblocktemplate","params":[{"capabilities":["coinbasetxn","workid","coinbase/append"],"rules":["segwit"]}],"id":1719008881479}
Reponse Data: Work queue depth exceeded

That response is part of our DigiHash test mining issue, could be related to the version bits warning clients are showing.

**Comment by beggsdl** [comment]
I am confident older versions are not mining a bunch of blocks. I’ve been getting >99% of blocks for quite a while. Every once in a while, I will notice one block that I did not get. Then today someone else started getting a good portion of the blocks. May you?

**Comment by JaredTate** [comment]
> I am confident older versions are not mining a bunch of blocks. I’ve been getting >99% of blocks for quite a while. Every once in a while, I will notice one block that I did not get. Then today someone else started getting a good portion of the blocks. May you?

Yes, it was us with Skein, but then as mentioned above... serious errors with them. Very perplexing. Nothing was showing up in the wallet but blocks still getting added to the chain.

**Comment by JaredTate** [comment]
I think we got some of the DigiHash pool issues sorted... getting some Tesnet sha256 blocks now with 8.22 RC4. 

![Screenshot 2024-06-21 at 5 12 55 PM](https://github.com/DigiByte-Core/digibyte/assets/13957390/88446479-13d6-43f5-b6a8-26a2ea271907)

![Screenshot 2024-06-21 at 5 13 05 PM](https://github.com/DigiByte-Core/digibyte/assets/13957390/b1f8a470-3a1a-4db1-9030-dde961ceb915)

https://digihash.digibyte.io/tbs

**Comment by beggsdl** [comment]
> I think we got some of the DigiHash pool issues sorted... getting some Tesnet sha256 blocks now with 8.22 RC4.

Nice!  Glad to see things are starting to get sorted out.

**Comment by JaredTate** [comment]
Ok we just test mined qubit, scrypt, sha256, skein on tesnet with 8.22 RC4 through digihash pool... it is mostly pool issues causing problems, but still have some consensus issues on testnet to debug. Will keep debugging and report back. Can't get odo to fire yet.

![Screenshot 2024-06-21 at 6 14 16 PM](https://github.com/DigiByte-Core/digibyte/assets/13957390/d40b22a2-98b8-4433-86d0-087c072ea937)
